env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    impliedStrict: true
rules:
  no-cond-assign: 0
  no-console: 0
  valid-jsdoc: 1
s